# Specify a non-default branch for pull requests for pip

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "fix-dependence"