# platform-admin has all privileges used
# of ClusterRoleBinding.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-admin
  labels:
    kubecube.io/rbac: "true"
    kubecube.io/role: "platform"
  annotations:
    kubecube.io/sync: "true"
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-platform-admin: "true"
rules: []
