# platform-admin has all privileges used
# of ClusterRoleBinding.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-to-platform-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-platform-admin: "true"
  annotations:
    kubecube.io/sync: "true"
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
      - pods/attach
      - pods/status
      - pods/execescalate
      - pods/exec
      - pods/portforward
      - pods/proxy
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - replicationcontrollers
      - replicationcontrollers/scale
      - replicationcontrollers/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - persistentvolumeclaims
      - persistentvolumeclaims/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - configmaps
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - services
      - services/proxy
      - services/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - serviceaccounts
    verbs:
      - impersonate
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/rollback
      - deployments/scale
      - deployments/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
      - replicasets
      - replicasets/scale
      - replicasets/status
      - controllerrevisions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - cronjobs
      - cronjobs/status
      - jobs
      - jobs/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - ingresses
      - ingresses/status
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - poddisruptionbudgets
      - poddisruptionbudgets/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - bindings
      - events
      - limitranges
      - resourcequotas
      - resourcequotas/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - namespaces
      - namespaces/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - localsubjectaccessreviews
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "*"
    resources:
      - rolebindings
      - roles
      - clusterrolebindings
      - clusterroles
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  # access to operate cuberesourcequota
  - apiGroups:
      - "*"
    resources:
      - cuberesourcequota
      - cuberesourcequota/finalizers
      - cuberesourcequota/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  # access to operate cluster
  - apiGroups:
      - "*"
    resources:
      - clusters
      - clusters/finalizers
      - clusters/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  # access to operate tenant
  - apiGroups:
      - "*"
    resources:
      - tenants
      - tenants/finalizers
      - tenants/status
      - projects
      - projects/finalizers
      - projects/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  # access to operate project
  - apiGroups:
      - "*"
    resources:
      - users
      - users/finalizers
      - users/status
      - keys
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"  #monitoring.kubecube.io
    resources:
      - dashboards
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*" #apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*" #monitoring.coreos.com
    resources:
      - alertmanagerconfigs
      - alertmanagers
      - podmonitors
      - probes
      - prometheuses
      - prometheusrules
      - servicemonitors
      - thanosrulers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*" #crd.projectcalico.org
    resources:
      - bgpconfigurations
      - bgppeers
      - blockaffinities
      - clusterinformations
      - felixconfigurations
      - globalnetworkpolicies
      - globalnetworksets
      - hostendpoints
      - ipamblocks
      - ipamconfigs
      - ipamhandles
      - ippools
      - kubecontrollersconfigurations
      - networkpolicies
      - networksets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*" #hnc.x-k8s.io
    resources:
      - hierarchyconfigurations
      - hncconfigurations
      - subnamespaceanchors
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*" #hotplug.kubecube.io
    resources:
      - hotplugs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*" #netease.com
    resources:
      - nodelogconfigs
      - logconfigs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*" #storage.kubecube.io
    resources:
      - cephs
      - nfs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update