# tenant admin has limited privileges under of
# tenant namespace used of RoleBinding.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  aggregate-to-tenant-admin-cluster
  labels:
    rbac.authorization.k8s.io/aggregate-to-tenant-admin-cluster: "true"
  annotations:
    kubecube.io/sync: "true"
rules:
  - apiGroups:
      - "*"
    resources:
      - componentstatuses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - namespaces/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*" #apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  ### KubeCube resource below
  - apiGroups:
      - "*"
    resources:
      - projects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "*"
    resources:
      - projects/finalizers
    verbs:
      - update
  - apiGroups:
      - "*"
    resources:
      - projects/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - cuberesourcequota
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - cuberesourcequota/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - "*"
    resources:
      - users
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - users/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - externalresources
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
---
