name: Go

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: go fmt check
        run: make fmt-check

      - name: Build
        run: make build

      - name: Test all
        run: go test -v $(go list ./... | grep -v /test/e2e)
