name: Makefile CI

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.1
        id: go
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        run: make lint